name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main # Trigger when workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      ## Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      ## Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      ## Step 3: Zip the Lambda function code
      - name: Zip Lambda function
        run: |
          zip -r lambda_function.zip lambda_function.py

      ## Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ## Step 5: Deploy to AWS Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name SpotifyFunction \
          --zip-file fileb://lambda_function.zip



